version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION}
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sales_managment
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    container_name: sm_database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_sm_database
    ports:
      - "2323:80"
    links:
      - database:db
    networks:
      - backend
networks:
  backend:
volumes:
  db-data:
